[package]
name = "blackjack_sim"
version = "1.1.1"
authors = ["ryotaro tanaka <ryotaro_tanaka@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.5"
